---
title: PTBins

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md', '/CONTRIBUTING.md']

permalink: pretty

collections:
  ptbins:
    output: true

defaults:
  - scope:
      path: '_ptbins'
    values:
      layout: bin
